### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by farocy79** [kunegis/konect-analysis#1]
Hi, 
I am using Linux 14.0.4 , and I am trying to install the analysis tool , but no idea what is happing, I did the konect toolbox and its working but the analysis many issue and the installation instruction not clear for me, if you can please explain the steps in other way and make it clear with details such link or copy /uni ??? which I have no idea what you mean! I feel its quite interesting tools but we need to know how to install properly. 
Thank you

**Comment by kunegis** [comment]
You're right, the installation instructions are not very complete.  I have written more detailed instructions in the file 'INSTALL' which is now available.  It should be much more clear what to do – but don't hesitate to ask if anything is unclear. 
Jérôme

**Comment by farocy79** [comment]
Thank you I will check it now :+1:

**Comment by farocy79** [comment]
Hello, 
The instructions are awesome, but when I tried to run an example I got this error with memory so I had to use 
" ulimit -v 5000000" 
also I needed a perl too other than that its worked perfect. 
Thank you :+1:

**Comment by kunegis** [comment]
Cheers, I added the missing information to the instructions.
