### ISSUE TITLE
Error in /tmp/

### ISSUE THREAD

**Issue by farocy79** [kunegis/konect-analysis#2]
Hello, I am using Ubuntu 16.04 and when I run the command below this is what I got ....

$nice ./mns @network.enron
network=enron: ./octave m/statistic_size.m
   /tmp/o.statistic_size.enron.log
*** error in /tmp/o.statistic_size.enron.log
main.stu:684:2: command for dat/statistic.size.enron failed with exit status 1
main.stu:386:2: dat/statistic.size.enron is needed by dat/check.enron
main.stu:379:19: dat/check.enron is needed by @check.enron
main.stu:40:21: @check.enron is needed by @network.enron

Would you please check what is the problem ? in output file dat I got three files info.enron , statistic.format.enron and statistic.weights.enron but nothing in plot file? 

Thank you

**Comment by kunegis** [comment]
Hi

Can you give us the content of the file /tmp/o.statistic_size.enron.log ?

**Comment by farocy79** [comment]
Yes sure 
its says just 
./octave: 49: ./octave: octave: not found
so now I'm looking for the reason.

**Comment by kunegis** [comment]
This tells you the reason:  You need to have Octave installed. Just do

$ sudo apt install octave

and you should be fine

Best

Jérôme

**Comment by farocy79** [comment]
Thank you I already did it and chmod for the file of .config/octave, and it did work but still having problem with plotting, so I am looking for the problem and if I did not find the solution I'll contact you. Thx again

**Comment by farocy79** [comment]
Sorry to bother but after fixing couple things in my computer, now I have this 

$ nice ./mns @network.enron
network=enron: ./matlab m/degree.m
	/tmp/m.degree.enron.log
main.stu:1106:1: file plot/degree.a.enron.eps was not built by command
main.stu:1104:20: plot/degree.a.enron.eps is needed by @degree.enron
dat/dep.network.enron:1:1: @degree.enron is needed by [dat/dep.network.enron]
main.stu:40:38: [dat/dep.network.enron] is needed by @network.enron

**Comment by kunegis** [comment]
Can you please provide the content of the file /tmp/m.degree.enron.log

**Comment by farocy79** [comment]
cat /tmp/m.degree.enron.log

                            < M A T L A B (R) >
                  Copyright 1984-2016 The MathWorks, Inc.
                   R2016b (9.1.0.441655) 64-bit (glnxa64)
                             September 7, 2016

Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/m 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/konect-toolbox/m 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib/matlab_bgl 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib/wafo-statistics 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib/wafo-misc 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib/gridxy 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/m 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/konect-toolbox/m 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib/matlab_bgl 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib/wafo-statistics 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib/wafo-misc 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib/gridxy 
 
For online documentation, see http://www.mathworks.com/support
For product information, visit www.mathworks.com.
 
Undefined function or variable 'konect_consts'.

Error in degree (line 37)
consts = konect_consts();
 
=== FINISHED ===

**Comment by kunegis** [comment]
Hi

All these directories should exist.  Can you do

ls -l /home/faswad/work/konect-analysis/

on your system ?

Jérôme

**Comment by farocy79** [comment]
The files is there 

total 276
drwxrwxr-x 8 faswad faswad  4096 Nov 28 13:32 .
drwxrwxr-x 7 faswad faswad  4096 Nov 28 14:14 ..
drwxrwxr-x 2 faswad faswad  4096 Nov 28 13:32 c
-rw-rw-r-- 1 faswad faswad 49000 Nov 28 13:32 colormap
-rw-rw-r-- 1 faswad faswad 35147 Nov 28 13:32 COPYING
-rw-rw-r-- 1 faswad faswad   218 Nov 28 13:32 DECOMPOSITIONS_ASYM
-rw-rw-r-- 1 faswad faswad   254 Nov 28 13:32 .gitignore
-rw-rw-r-- 1 faswad faswad  5296 Nov 28 13:32 INSTALL
drwxrwxr-x 2 faswad faswad  4096 Nov 28 13:32 jl
-rwxr-xr-x 1 faswad faswad   258 Nov 28 13:32 julia
-rwxr-xr-x 1 faswad faswad   123 Nov 28 13:32 ktop
drwxrwxr-x 4 faswad faswad  4096 Nov 28 13:32 lib
drwxrwxr-x 2 faswad faswad 12288 Nov 28 13:32 m
-rw-rw-r-- 1 faswad faswad 39712 Nov 28 13:32 main.stu
-rw-rw-r-- 1 faswad faswad 12968 Nov 28 13:32 Makefile.old
-rwxr-xr-x 1 faswad faswad  4180 Nov 28 13:32 matlab
-rwxr-xr-x 1 faswad faswad   742 Nov 28 13:32 mns
-rwxr-xr-x 1 faswad faswad  1343 Nov 28 13:32 octave
drwxrwxr-x 3 faswad faswad  4096 Nov 28 13:32 pl
-rw-rw-r-- 1 faswad faswad   176 Nov 28 13:32 PLOTS
-rw-rw-r-- 1 faswad faswad    46 Nov 28 13:32 PLOTS_ASYM
-rw-rw-r-- 1 faswad faswad    14 Nov 28 13:32 PLOTS_SQUARE
-rw-rw-r-- 1 faswad faswad    79 Nov 28 13:32 PLOTS_TIME
-rw-rw-r-- 1 faswad faswad   857 Nov 28 13:32 PLOTTING
-rw-rw-r-- 1 faswad faswad  3601 Nov 28 13:32 README
-rw-rw-r-- 1 faswad faswad   682 Nov 28 13:32 runtime.source
-rw-rw-r-- 1 faswad faswad   356 Nov 28 13:32 SCATTERS
drwxrwxr-x 2 faswad faswad  4096 Nov 28 13:32 sh
-rw-rw-r-- 1 faswad faswad   248 Nov 28 13:32 STATISTICS
-rwxr-xr-x 1 faswad faswad  2118 Nov 28 13:32 status
-rw-rw-r-- 1 faswad faswad 14726 Nov 28 13:32 TODO

**Comment by farocy79** [comment]
the output for the file is 
cat /tmp/m.degree.enron.log

                            < M A T L A B (R) >
                  Copyright 1984-2016 The MathWorks, Inc.
                   R2016b (9.1.0.441655) 64-bit (glnxa64)
                             September 7, 2016

Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/konect-toolbox/m 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib/matlab_bgl 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib/wafo-statistics 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib/wafo-misc 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/konect-toolbox/m 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib/matlab_bgl 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib/wafo-statistics 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib/wafo-misc 
 
For online documentation, see http://www.mathworks.com/support
For product information, visit www.mathworks.com.
 
Undefined function or variable 'konect_consts'.

Error in degree (line 37)
consts = konect_consts();
 
=== FINISHED ===

**Comment by kunegis** [comment]
Hi

Did you follow all steps from the installation instructions:

https://github.com/kunegis/konect-analysis/blob/master/INSTALL

In particular, step number (4) consists in linking several other 
directories into konect-analysis.  I see that you're missing at least 
konect-toolbox.

Best

Jérôme

**Comment by farocy79** [comment]
Yes I did that and I have no issuer when I did it, but to make sure I'll repeat the steps again, thank you for your quick response

**Comment by farocy79** [comment]
I did, and it showing same error, 

sudo nice ./mns @network.enron
[sudo] password for faswad: 
>dat/statistic.format.enron <uni/out.enron network=enron: sh/network-format
>dat/statistic.weights.enron <uni/out.enron network=enron: sh/network-weights
>dat/info.enron <uni/out.enron network=enron: sh/network-info
>MATLABPATH: printf "$PWD/m/:$PWD/konect-toolbox/m:$PWD/lib/:$PWD/lib/matlab_bgl/:$PWD/lib/wafo-statistics/:$PWD/lib/wafo-misc/:$PWD/lib/gridxy"
network=enron: ./octave m/statistic_size.m
   /tmp/o.statistic_size.enron.log
network=enron: ./octave m/statistic_lines.m
   /tmp/o.statistic_lines.enron.log
network=enron: ./octave m/check.m && echo OK >dat/check.$network
   /tmp/o.check.enron.log
>dat/networks.list: sh/mkdatasetlist
Building dat/networks.asc
>dat/NETWORKS_SQUARE: grep -E " (a|)sym " dat/networks.asc | cut -f1 -d ' '
>dat/NETWORKS_ASYM: grep -E " asym " dat/networks.asc | cut -f1 -d ' '
>dat/NETWORKS_TIME: grep ' t ' dat/networks.asc | cut -d ' ' -f 1
>dat/dep.network.enron network=enron: sh/dep-network
network=enron: ./matlab m/degree.m
	/tmp/m.degree.enron.log
main.stu:1106:1: file plot/degree.a.enron.eps was not built by command
main.stu:1104:20: plot/degree.a.enron.eps is needed by @degree.enron
dat/dep.network.enron:1:1: @degree.enron is needed by [dat/dep.network.enron]
main.stu:40:38: [dat/dep.network.enron] is needed by @network.enron

**Comment by farocy79** [comment]
It seems some packages are not support anymore like loglog
cat /tmp/m.degree.enron.log

                            < M A T L A B (R) >
                  Copyright 1984-2016 The MathWorks, Inc.
                   R2016b (9.1.0.441655) 64-bit (glnxa64)
                             September 7, 2016

Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib/matlab_bgl 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib/wafo-statistics 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib/wafo-misc 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib/matlab_bgl 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib/wafo-statistics 
Warning: Name is nonexistent or not a directory:
/home/faswad/work/konect-analysis/lib/wafo-misc 
 
For online documentation, see http://www.mathworks.com/support
For product information, visit www.mathworks.com.
 

network =

enron

Degree distribution...
Error using loglog
This functionality is no longer supported under the -nojvm startup option. For
more information, see "Changes to -nojvm Startup Option" in the MATLAB Release
Notes. To view the release note in your system browser, run
web('http://www.mathworks.com/help/matlab/release-notes.html#btsurqv-6',
'-browser').

Error in degree_print (line 48)
loglog(ra, fq, point_style, 'Color', colors.(type), 'MarkerSize', marker_size);

Error in degree (line 165)
    degree_print(A_x + A_x', power(1), xmin(1), pvalue(1), 'Degree (d)', 'a');
 
=== FINISHED ===

**Comment by kunegis** [comment]
Hi

KONECT Analysis was developed using version 2009B of Matlab :/

We have not tried it with newer versions, and given that the Matlab 
language is not standardized and proprietary, I wouldn't be surprised if 
the API of the loglog() function has changed. The same probably also 
goes for other functions.  You may try to adapt the KONECT code to newer 
Matlab versions, if you know enough Matlab, or you may try to find an 
old version of Matlab, but I have no idea where such a version could be 
found.  The inconveniences of proprietary software, indeed.  If you are 
lucky, there may be a compatibility option in newer Matlab versions, but 
I have not heard of such a thing.  Alternatively, you can also try to 
switch from Matlab to Octave (in line 1106 of main.stu), but then you'll 
probably get other errors.  I'm afraid that's as much as I can help you 
with here.

Best

Jérôme

**Comment by farocy79** [comment]
I understand, I will try to find a way to fix the problem, and I really appropriate your help, I believe that your project is very helpful and I wish the best for you. Thank you again
