### ISSUE TITLE
[konect-analysis] command for dat/check.enron failed with exit status 1

### ISSUE THREAD

**Issue by Oolev** [kunegis/konect-analysis#3]
I followed the setup instructions and installed all necessary libs (I am on Ubuntu 18.04), so far I tried two datasets from konect website, but I keep getting the same error message for both:

> Building dat/statistic.size.enron
Building dat/info.enron
network=enron: ./octave m/statistic_lines.m
	/tmp/o.statistic_lines.enron.log
network=enron: ./octave m/check.m
	/tmp/o.check.enron.log
*** error in /tmp/o.check.enron.log
main.stu:501:2: command for dat/check.enron failed with exit status 1
main.stu:490:19: dat/check.enron is needed by @check.enron
dat/dep.network.enron:1:1: @check.enron is needed by [dat/dep.network.enron]
main.stu:53:22: [dat/dep.network.enron] is needed by @network.enron
stu: Removing file dat/check.enron because command failed

I wonder what's going wrong. The error seems to stem from this line in main.stu file:

`{
	./octave m/check.m 
}
`

I'd appreciate if you could spare some thoughts on this issue. 
Thanks in advance

**Comment by kunegis** [comment]
Hi
The error message is in the file /tmp/o.check.enron.log
Cheers
Jérôme

**Comment by Oolev** [comment]
Thanks for the fast reply.
Sorry but I can't locate the file in `~/work/konect-analysis,` the whole tmp directory is not found

**Comment by kunegis** [comment]
The filename "/tmp/o.check.enron.log" starts with a slash, so it's a "global" file if you will.  It's in /tmp/.

PS, the used temporary directory can be changed by setting $TMPDIR.  The default is /tmp/.

**Comment by Oolev** [comment]
Thanks, I got the file contents:

> tag_acyclic = 0
tag_clique = 0
tag_incomplete = 0
tag_lcc = 0
tag_loop = 0
tag_lowmultiplicity = 0
tag_nonreciprocal = 0
tag_tournament = 0
tag_zeroweight = 0
attempting to save variables to 'octave-workspace'...
save to 'octave-workspace' complete
terminate called after throwing an instance of 'octave::exit_exception'
panic: Aborted -- stopping myself...
attempting to save variables to 'octave-workspace'...
save to 'octave-workspace' complete


After editing access permissions in ~/work and ~/data, the file in question disappears from the error message. However the following message appears, it says it can't find dat-tmp, and aborts afterwards: 

> Building dat/statistic.lines.mit
Building dat/README.mit
	/tmp/o.statistic_lines.mit.log
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/({\\(.){ <-- HERE (\\?\w{1,2})}})/ at lib/LaTeX/ToUnicode.pm line 32.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/(\\(.){ <-- HERE (\\?\w{1,2})})/ at lib/LaTeX/ToUnicode.pm line 35.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/({\\(.){ <-- HERE (\\?\w{1,2})}})/ at lib/LaTeX/ToUnicode.pm line 32.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/(\\(.){ <-- HERE (\\?\w{1,2})})/ at lib/LaTeX/ToUnicode.pm line 35.
Successfully built dat/statistic.lines.mit
main.stu:1850:1: expected the file without command and without dependencies dat-tmp to exist, but it does not
main.stu:1825:6: dat-tmp is needed by dat/download.tsv.mit.tar.bz2
main.stu:1744:17: dat/download.tsv.mit.tar.bz2 is needed by @tsv.mit
dat/dep.network.mit:2:1: @tsv.mit is needed by [dat/dep.network.mit]
main.stu:53:22: [dat/dep.network.mit] is needed by @network.mit
stu: Terminating all jobs
stu: Terminating all jobs
stu: Removing partially built files (1)

**Comment by kunegis** [comment]
Hi
The Perl message doesn't seem to be a problem.  (Something is deprecated but the Perl version can handle it.)
The real error is:  expected the file without command and without dependencies dat-tmp to exist, but it does not.
I have updated the file INSTALL to document this.  You have to do 

$ ln -s /tmp ./dat-tmp

(Instead of /tmp you can also specify another directory to be used as a temporary directory.)

**Comment by Oolev** [comment]
This solves almost everything, thanks! Unfortunately now my matlab license checkout has failed. I'll post updates as soon I fix this issue.

**Comment by kunegis** [comment]
Cheers!

**Comment by Oolev** [comment]
Hello, 

I'd like to point out the few issues I encountered so far, and what solutions I attempted as follows:

`(1)octave::exit_exception:`
After activating my matlab license and running the konect analysis, I had the following error:

> terminate called after throwing an instance of 'octave::exit_exception'
panic: Aborted -- stopping myself...
attempting to save variables to 'octave-workspace'...
save to 'octave-workspace' complete
Aborted (core dumped)


Following this link:
https://savannah.gnu.org/bugs/?50707
It appears calling `exit()  resulted` in the above error which seems to be a result of a bug in octave 4.2

Removing `exit(0);` from the files: `check_failed.m and` `check_successful.m` resolved this error.

(2)Missing module:
Also, the following module: Statisitics and Machine Learning toolbox was required, maybe you'd like to add it to konect requirements' list.

That's all. After solving these issues, the building went successfully and the plots were generated, until reaching this error:

> Building dat/statistic_time.full.avgdegree.mit
Building syngraphy
main.stu:1913:2: command for syngraphy/ failed with exit status 1
main.stu:1900:8: syngraphy/ is needed by @syngraphy.mit
dat/dep.network.mit:68:1: @syngraphy.mit is needed by [dat/dep.network.mit]
main.stu:53:22: [dat/dep.network.mit] is needed by @network.mit
stu: Terminating all jobs
stu: Terminating all jobs

At this stage, I failed at patching this one, maybe you'd like to check it.

Thanks again.

**Comment by kunegis** [comment]
Hi

(1) exit() is definitely needed; better use a version that has it, because otherwise no error can be reported by Octave code.

(2) I don't have an official list of modules that are needed; users will have to find out by hand what is needed.

(3) "Syngraphy" is experimental code, and may need additional setup.

What target are you running that starts Syngraphy?

**Comment by Oolev** [comment]
Thanks for the comments,

About the last point, I am currently running everything for one network ( `@network.$network` ) , I am experimenting with `mit` reality mining network.

**Comment by kunegis** [comment]
Ok, if you run everything for one network, please be advised that:
(1) Some things are very experimental, so may be full of bugs (potentially), and may not be easy to interpret anyway (without knowing what I was thinking when I wrote it)
(2) Some things may take very long to compute.  Better use stu -j then, and don't hesitate to kill those processes that take too long

**Comment by kunegis** [comment]
Btw, as for that syngraphy error:  I think it's just the syngraphy/ directory missing -- that's an experimental method for graph visualization that if I remember correctly uses its own directory.

**Comment by Oolev** [comment]
I see, I'll take that into consideration.

I think this solves all the major issues, so I'll set the thread as closed.

Thanks for the prompt replies and the advice.
